/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyCheckIn {
  'localDate' : string,
  'medicationChanges' : boolean,
  'dizziness' : boolean,
  'alcoholIntake' : boolean,
  'fatigue' : boolean,
  'sleepQualityGood' : boolean,
  'visionIssues' : boolean,
  'unsteadiness' : boolean,
  'actualFall' : boolean,
  'nearFall' : boolean,
  'timestamp' : Time,
  'newPain' : boolean,
}
export type HealthCondition = { 'osteoporosis' : null } |
  { 'visionImpairment' : null } |
  { 'dizziness' : null } |
  { 'other' : string } |
  { 'parkinsons' : null } |
  { 'balanceDisorder' : null } |
  { 'arthritis' : null };
export type MobilityAid = { 'other' : string } |
  { 'cane' : null } |
  { 'none' : null } |
  { 'wheelchair' : null } |
  { 'walker' : null };
export interface RiskAssessment {
  'contributingFactors' : Array<string>,
  'riskLevel' : RiskLevel,
  'riskScore' : bigint,
}
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Sex = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null } |
  { 'unknown' : null };
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'sex' : [] | [Sex],
  'hadFallLast12Months' : boolean,
  'hasBalanceAffectingMedications' : boolean,
  'heightCm' : [] | [number],
  'mobilityAids' : Array<MobilityAid>,
  'weightKg' : [] | [number],
  'healthConditions' : Array<HealthCondition>,
  'fallCountLast12Months' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerCheckIns' : ActorMethod<[bigint], Array<DailyCheckIn>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheckInByDate' : ActorMethod<[string], [] | [DailyCheckIn]>,
  'getCurrentRiskAssessment' : ActorMethod<[], [] | [RiskAssessment]>,
  'getRiskHistory' : ActorMethod<
    [Principal, bigint],
    Array<[DailyCheckIn, RiskAssessment]>
  >,
  'getUserCheckIns' : ActorMethod<[Principal, bigint], Array<DailyCheckIn>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCheckIn' : ActorMethod<[DailyCheckIn], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];