/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const DailyCheckIn = IDL.Record({
  'localDate' : IDL.Text,
  'medicationChanges' : IDL.Bool,
  'dizziness' : IDL.Bool,
  'alcoholIntake' : IDL.Bool,
  'fatigue' : IDL.Bool,
  'sleepQualityGood' : IDL.Bool,
  'visionIssues' : IDL.Bool,
  'unsteadiness' : IDL.Bool,
  'actualFall' : IDL.Bool,
  'nearFall' : IDL.Bool,
  'timestamp' : Time,
  'newPain' : IDL.Bool,
});
export const Sex = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
  'unknown' : IDL.Null,
});
export const MobilityAid = IDL.Variant({
  'other' : IDL.Text,
  'cane' : IDL.Null,
  'none' : IDL.Null,
  'wheelchair' : IDL.Null,
  'walker' : IDL.Null,
});
export const HealthCondition = IDL.Variant({
  'osteoporosis' : IDL.Null,
  'visionImpairment' : IDL.Null,
  'dizziness' : IDL.Null,
  'other' : IDL.Text,
  'parkinsons' : IDL.Null,
  'balanceDisorder' : IDL.Null,
  'arthritis' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'sex' : IDL.Opt(Sex),
  'hadFallLast12Months' : IDL.Bool,
  'hasBalanceAffectingMedications' : IDL.Bool,
  'heightCm' : IDL.Opt(IDL.Float64),
  'mobilityAids' : IDL.Vec(MobilityAid),
  'weightKg' : IDL.Opt(IDL.Float64),
  'healthConditions' : IDL.Vec(HealthCondition),
  'fallCountLast12Months' : IDL.Nat,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const RiskAssessment = IDL.Record({
  'contributingFactors' : IDL.Vec(IDL.Text),
  'riskLevel' : RiskLevel,
  'riskScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerCheckIns' : IDL.Func([IDL.Nat], [IDL.Vec(DailyCheckIn)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckInByDate' : IDL.Func([IDL.Text], [IDL.Opt(DailyCheckIn)], ['query']),
  'getCurrentRiskAssessment' : IDL.Func(
      [],
      [IDL.Opt(RiskAssessment)],
      ['query'],
    ),
  'getRiskHistory' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Vec(IDL.Tuple(DailyCheckIn, RiskAssessment))],
      ['query'],
    ),
  'getUserCheckIns' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Vec(DailyCheckIn)],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCheckIn' : IDL.Func([DailyCheckIn], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const DailyCheckIn = IDL.Record({
    'localDate' : IDL.Text,
    'medicationChanges' : IDL.Bool,
    'dizziness' : IDL.Bool,
    'alcoholIntake' : IDL.Bool,
    'fatigue' : IDL.Bool,
    'sleepQualityGood' : IDL.Bool,
    'visionIssues' : IDL.Bool,
    'unsteadiness' : IDL.Bool,
    'actualFall' : IDL.Bool,
    'nearFall' : IDL.Bool,
    'timestamp' : Time,
    'newPain' : IDL.Bool,
  });
  const Sex = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const MobilityAid = IDL.Variant({
    'other' : IDL.Text,
    'cane' : IDL.Null,
    'none' : IDL.Null,
    'wheelchair' : IDL.Null,
    'walker' : IDL.Null,
  });
  const HealthCondition = IDL.Variant({
    'osteoporosis' : IDL.Null,
    'visionImpairment' : IDL.Null,
    'dizziness' : IDL.Null,
    'other' : IDL.Text,
    'parkinsons' : IDL.Null,
    'balanceDisorder' : IDL.Null,
    'arthritis' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'sex' : IDL.Opt(Sex),
    'hadFallLast12Months' : IDL.Bool,
    'hasBalanceAffectingMedications' : IDL.Bool,
    'heightCm' : IDL.Opt(IDL.Float64),
    'mobilityAids' : IDL.Vec(MobilityAid),
    'weightKg' : IDL.Opt(IDL.Float64),
    'healthConditions' : IDL.Vec(HealthCondition),
    'fallCountLast12Months' : IDL.Nat,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const RiskAssessment = IDL.Record({
    'contributingFactors' : IDL.Vec(IDL.Text),
    'riskLevel' : RiskLevel,
    'riskScore' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerCheckIns' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DailyCheckIn)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckInByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DailyCheckIn)],
        ['query'],
      ),
    'getCurrentRiskAssessment' : IDL.Func(
        [],
        [IDL.Opt(RiskAssessment)],
        ['query'],
      ),
    'getRiskHistory' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Vec(IDL.Tuple(DailyCheckIn, RiskAssessment))],
        ['query'],
      ),
    'getUserCheckIns' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Vec(DailyCheckIn)],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCheckIn' : IDL.Func([DailyCheckIn], [], []),
  });
};

export const init = ({ IDL }) => { return []; };