/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type HealthCondition = {
    __kind__: "osteoporosis";
    osteoporosis: null;
} | {
    __kind__: "visionImpairment";
    visionImpairment: null;
} | {
    __kind__: "dizziness";
    dizziness: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "parkinsons";
    parkinsons: null;
} | {
    __kind__: "balanceDisorder";
    balanceDisorder: null;
} | {
    __kind__: "arthritis";
    arthritis: null;
};
export type Time = bigint;
export interface DailyCheckIn {
    localDate: string;
    medicationChanges: boolean;
    dizziness: boolean;
    alcoholIntake: boolean;
    fatigue: boolean;
    sleepQualityGood: boolean;
    visionIssues: boolean;
    unsteadiness: boolean;
    actualFall: boolean;
    nearFall: boolean;
    timestamp: Time;
    newPain: boolean;
}
export type MobilityAid = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "cane";
    cane: null;
} | {
    __kind__: "none";
    none: null;
} | {
    __kind__: "wheelchair";
    wheelchair: null;
} | {
    __kind__: "walker";
    walker: null;
};
export interface RiskAssessment {
    contributingFactors: Array<string>;
    riskLevel: RiskLevel;
    riskScore: bigint;
}
export interface UserProfile {
    age: bigint;
    sex?: Sex;
    hadFallLast12Months: boolean;
    hasBalanceAffectingMedications: boolean;
    heightCm?: number;
    mobilityAids: Array<MobilityAid>;
    weightKg?: number;
    healthConditions: Array<HealthCondition>;
    fallCountLast12Months: bigint;
}
export enum RiskLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Sex {
    other = "other",
    female = "female",
    male = "male",
    unknown_ = "unknown"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerCheckIns(limit: bigint): Promise<Array<DailyCheckIn>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCheckInByDate(date: string): Promise<DailyCheckIn | null>;
    getCurrentRiskAssessment(): Promise<RiskAssessment | null>;
    getRiskHistory(user: Principal, limit: bigint): Promise<Array<[DailyCheckIn, RiskAssessment]>>;
    getUserCheckIns(user: Principal, limit: bigint): Promise<Array<DailyCheckIn>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitCheckIn(checkIn: DailyCheckIn): Promise<void>;
}
import type { DailyCheckIn as _DailyCheckIn, HealthCondition as _HealthCondition, MobilityAid as _MobilityAid, RiskAssessment as _RiskAssessment, RiskLevel as _RiskLevel, Sex as _Sex, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerCheckIns(arg0: bigint): Promise<Array<DailyCheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerCheckIns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerCheckIns(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckInByDate(arg0: string): Promise<DailyCheckIn | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInByDate(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInByDate(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentRiskAssessment(): Promise<RiskAssessment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentRiskAssessment();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentRiskAssessment();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiskHistory(arg0: Principal, arg1: bigint): Promise<Array<[DailyCheckIn, RiskAssessment]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskHistory(arg0, arg1);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskHistory(arg0, arg1);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserCheckIns(arg0: Principal, arg1: bigint): Promise<Array<DailyCheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCheckIns(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCheckIns(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitCheckIn(arg0: DailyCheckIn): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCheckIn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCheckIn(arg0);
            return result;
        }
    }
}
function from_candid_HealthCondition_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthCondition): HealthCondition {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_MobilityAid_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MobilityAid): MobilityAid {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_RiskAssessment_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskAssessment): RiskAssessment {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Sex_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sex): Sex {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyCheckIn]): DailyCheckIn | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RiskAssessment]): RiskAssessment | null {
    return value.length === 0 ? null : from_candid_RiskAssessment_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sex]): Sex | null {
    return value.length === 0 ? null : from_candid_Sex_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contributingFactors: Array<string>;
    riskLevel: _RiskLevel;
    riskScore: bigint;
}): {
    contributingFactors: Array<string>;
    riskLevel: RiskLevel;
    riskScore: bigint;
} {
    return {
        contributingFactors: value.contributingFactors,
        riskLevel: from_candid_RiskLevel_n22(_uploadFile, _downloadFile, value.riskLevel),
        riskScore: value.riskScore
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    sex: [] | [_Sex];
    hadFallLast12Months: boolean;
    hasBalanceAffectingMedications: boolean;
    heightCm: [] | [number];
    mobilityAids: Array<_MobilityAid>;
    weightKg: [] | [number];
    healthConditions: Array<_HealthCondition>;
    fallCountLast12Months: bigint;
}): {
    age: bigint;
    sex?: Sex;
    hadFallLast12Months: boolean;
    hasBalanceAffectingMedications: boolean;
    heightCm?: number;
    mobilityAids: Array<MobilityAid>;
    weightKg?: number;
    healthConditions: Array<HealthCondition>;
    fallCountLast12Months: bigint;
} {
    return {
        age: value.age,
        sex: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.sex)),
        hadFallLast12Months: value.hadFallLast12Months,
        hasBalanceAffectingMedications: value.hasBalanceAffectingMedications,
        heightCm: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.heightCm)),
        mobilityAids: from_candid_vec_n10(_uploadFile, _downloadFile, value.mobilityAids),
        weightKg: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.weightKg)),
        healthConditions: from_candid_vec_n13(_uploadFile, _downloadFile, value.healthConditions),
        fallCountLast12Months: value.fallCountLast12Months
    };
}
function from_candid_tuple_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_DailyCheckIn, _RiskAssessment]): [DailyCheckIn, RiskAssessment] {
    return [
        value[0],
        from_candid_RiskAssessment_n20(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    cane: null;
} | {
    none: null;
} | {
    wheelchair: null;
} | {
    walker: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "cane";
    cane: null;
} | {
    __kind__: "none";
    none: null;
} | {
    __kind__: "wheelchair";
    wheelchair: null;
} | {
    __kind__: "walker";
    walker: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "cane" in value ? {
        __kind__: "cane",
        cane: value.cane
    } : "none" in value ? {
        __kind__: "none",
        none: value.none
    } : "wheelchair" in value ? {
        __kind__: "wheelchair",
        wheelchair: value.wheelchair
    } : "walker" in value ? {
        __kind__: "walker",
        walker: value.walker
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    osteoporosis: null;
} | {
    visionImpairment: null;
} | {
    dizziness: null;
} | {
    other: string;
} | {
    parkinsons: null;
} | {
    balanceDisorder: null;
} | {
    arthritis: null;
}): {
    __kind__: "osteoporosis";
    osteoporosis: null;
} | {
    __kind__: "visionImpairment";
    visionImpairment: null;
} | {
    __kind__: "dizziness";
    dizziness: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "parkinsons";
    parkinsons: null;
} | {
    __kind__: "balanceDisorder";
    balanceDisorder: null;
} | {
    __kind__: "arthritis";
    arthritis: null;
} {
    return "osteoporosis" in value ? {
        __kind__: "osteoporosis",
        osteoporosis: value.osteoporosis
    } : "visionImpairment" in value ? {
        __kind__: "visionImpairment",
        visionImpairment: value.visionImpairment
    } : "dizziness" in value ? {
        __kind__: "dizziness",
        dizziness: value.dizziness
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "parkinsons" in value ? {
        __kind__: "parkinsons",
        parkinsons: value.parkinsons
    } : "balanceDisorder" in value ? {
        __kind__: "balanceDisorder",
        balanceDisorder: value.balanceDisorder
    } : "arthritis" in value ? {
        __kind__: "arthritis",
        arthritis: value.arthritis
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "medium" in value ? RiskLevel.medium : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
} | {
    unknown: null;
}): Sex {
    return "other" in value ? Sex.other : "female" in value ? Sex.female : "male" in value ? Sex.male : "unknown" in value ? Sex.unknown : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MobilityAid>): Array<MobilityAid> {
    return value.map((x)=>from_candid_MobilityAid_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HealthCondition>): Array<HealthCondition> {
    return value.map((x)=>from_candid_HealthCondition_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_DailyCheckIn, _RiskAssessment]>): Array<[DailyCheckIn, RiskAssessment]> {
    return value.map((x)=>from_candid_tuple_n25(_uploadFile, _downloadFile, x));
}
function to_candid_HealthCondition_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HealthCondition): _HealthCondition {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_MobilityAid_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MobilityAid): _MobilityAid {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Sex_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sex): _Sex {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    sex?: Sex;
    hadFallLast12Months: boolean;
    hasBalanceAffectingMedications: boolean;
    heightCm?: number;
    mobilityAids: Array<MobilityAid>;
    weightKg?: number;
    healthConditions: Array<HealthCondition>;
    fallCountLast12Months: bigint;
}): {
    age: bigint;
    sex: [] | [_Sex];
    hadFallLast12Months: boolean;
    hasBalanceAffectingMedications: boolean;
    heightCm: [] | [number];
    mobilityAids: Array<_MobilityAid>;
    weightKg: [] | [number];
    healthConditions: Array<_HealthCondition>;
    fallCountLast12Months: bigint;
} {
    return {
        age: value.age,
        sex: value.sex ? candid_some(to_candid_Sex_n28(_uploadFile, _downloadFile, value.sex)) : candid_none(),
        hadFallLast12Months: value.hadFallLast12Months,
        hasBalanceAffectingMedications: value.hasBalanceAffectingMedications,
        heightCm: value.heightCm ? candid_some(value.heightCm) : candid_none(),
        mobilityAids: to_candid_vec_n30(_uploadFile, _downloadFile, value.mobilityAids),
        weightKg: value.weightKg ? candid_some(value.weightKg) : candid_none(),
        healthConditions: to_candid_vec_n33(_uploadFile, _downloadFile, value.healthConditions),
        fallCountLast12Months: value.fallCountLast12Months
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sex): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} | {
    unknown: null;
} {
    return value == Sex.other ? {
        other: null
    } : value == Sex.female ? {
        female: null
    } : value == Sex.male ? {
        male: null
    } : value == Sex.unknown ? {
        unknown_: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "cane";
    cane: null;
} | {
    __kind__: "none";
    none: null;
} | {
    __kind__: "wheelchair";
    wheelchair: null;
} | {
    __kind__: "walker";
    walker: null;
}): {
    other: string;
} | {
    cane: null;
} | {
    none: null;
} | {
    wheelchair: null;
} | {
    walker: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "cane" ? {
        cane: value.cane
    } : value.__kind__ === "none" ? {
        none: value.none
    } : value.__kind__ === "wheelchair" ? {
        wheelchair: value.wheelchair
    } : value.__kind__ === "walker" ? {
        walker: value.walker
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "osteoporosis";
    osteoporosis: null;
} | {
    __kind__: "visionImpairment";
    visionImpairment: null;
} | {
    __kind__: "dizziness";
    dizziness: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "parkinsons";
    parkinsons: null;
} | {
    __kind__: "balanceDisorder";
    balanceDisorder: null;
} | {
    __kind__: "arthritis";
    arthritis: null;
}): {
    osteoporosis: null;
} | {
    visionImpairment: null;
} | {
    dizziness: null;
} | {
    other: string;
} | {
    parkinsons: null;
} | {
    balanceDisorder: null;
} | {
    arthritis: null;
} {
    return value.__kind__ === "osteoporosis" ? {
        osteoporosis: value.osteoporosis
    } : value.__kind__ === "visionImpairment" ? {
        visionImpairment: value.visionImpairment
    } : value.__kind__ === "dizziness" ? {
        dizziness: value.dizziness
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "parkinsons" ? {
        parkinsons: value.parkinsons
    } : value.__kind__ === "balanceDisorder" ? {
        balanceDisorder: value.balanceDisorder
    } : value.__kind__ === "arthritis" ? {
        arthritis: value.arthritis
    } : value;
}
function to_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MobilityAid>): Array<_MobilityAid> {
    return value.map((x)=>to_candid_MobilityAid_n31(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<HealthCondition>): Array<_HealthCondition> {
    return value.map((x)=>to_candid_HealthCondition_n34(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
